### PR TITLE
blog: add materials (esp32 things)

### PR DESCRIPTION
**Pull request by Eggrror404**
_25時、GitHubで。_

adds esp32 materials

### CODE REVIEW

**Comment by HeyLoon** [comment]
You should go to sleep

**Comment by Eggrror404** [comment]
> You should go to sleep

true im dying rn

**Comment by Eggrror404** [comment]
peak writing

**Comment by Eggrror404** [comment]
@HeyLoon 電機社有救了

**Comment by Eggrror404** [comment]
@HeyLoon 直接強制過關 不做環評了謝謝

**Pull request merged**
