### PR TITLE
feat: minor UI updates

### PR DESCRIPTION
**Pull request by Eggrror404**
probably the last update i'll do on here util next year

fixes ui / impl things, adds things that i wanted

### CODE REVIEW

**Comment by Eggrror404** [comment]
currently left on draft because there might be something that i wanted and forgot about.

**Review by HeyLoon — APPROVED** [review]
Unimpeachable

**Comment by Eggrror404** [comment]
this is #99 btw

~~_we should just open issue #100 to celebrate it_~~

**Comment by HeyLoon** [comment]
> this is #99 btw
> 
> ~~_we should just open issue #100 to celebrate it_~~

You opened at least 98 of the 99 🥰
hardo workingu man

**Pull request merged**
